- hosts: all
  gather_facts: no
  become: yes
  become_method: sudo

  tasks:
    - name: Update dnf packages
      dnf:
        name: '*'
        state: latest
        use_backend: dnf

    - name: Install required packages
      dnf:
        name:
          - dnf-utils
          - device-mapper-persistent-data
          - lvm2
        state: present
        use_backend: dnf

    - name: Set up the Docker stable repository
      dnf:
        name: dnf-plugins-core
        state: present
        use_backend: dnf

    - name: Add Docker repository
      ansible.builtin.command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker
      dnf:
        name: docker-ce
        state: present
        use_backend: dnf

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull hello-world image
      community.docker.docker_image:
        name: hello-world
        source: pull

    - name: Run hello-world container and display output
      command: docker run --rm hello-world
      register: hello_world_output

    - name: Display hello-world output
      debug:
        var: hello_world_output.stdout