- hosts: all
  gather_facts: no

  tasks:
    - name: Install ansible-galaxy requirements
      ansible.builtin.command: ansible-galaxy collection install -r ./collections/requirements.yml

    - name: Install Docker
      community.general.package:
        name: docker-ce
        state: present
    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull hello-world image
      community.docker.docker_image:
        name: hello-world
        source: pull

    - name: Run hello-world container and display output
      command: docker run --rm hello-world
      register: hello_world_output

    - name: Display hello-world output
      debug:
        var: hello_world_output.stdout