- hosts: all
  gather_facts: no

  tasks:
    - name: Update yum packages
      command: yum update -y

    - name: Install required packages
      command: yum install -y yum-utils device-mapper-persistent-data lvm2

    - name: Set up the Docker stable repository
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker
      command: yum install -y docker-ce docker-ce-cli containerd.io

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull hello-world image
      community.docker.docker_image:
        name: hello-world
        source: pull

    - name: Run hello-world container and display output
      command: docker run --rm hello-world
      register: hello_world_output

    - name: Display hello-world output
      debug:
        var: hello_world_output.stdout