- hosts: all
  gather_facts: no

  tasks:
    - name: Install Docker
      ansible.builtin.command: |
        if ! command -v docker &> /dev/null; then
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
        fi

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull hello-world image
      community.docker.docker_image:
        name: hello-world
        source: pull

    - name: Run hello-world container and display output
      command: docker run --rm hello-world
      register: hello_world_output

    - name: Display hello-world output
      debug:
        var: hello_world_output.stdout