- hosts: all
  gather_facts: no
  become: true
  become_method: sudo

  tasks:
    - name: Update yum packages
      yum:
        name: '*'
        state: latest
        use_backend: yum

    - name: Install required packages
      yum:
        name:
          - yum-utils
        state: present
        use_backend: yum

    - name: Set up the Docker stable repository
      yum_repository:
        name: docker-ce
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo
        gpgcheck: yes
        enabled: yes
        gpgkey: https://download.docker.com/linux/centos/gpg

    - name: Install Docker
      yum:
        name: docker-ce
        state: present
        use_backend: yum

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull hello-world image
      community.docker.docker_image:
        name: hello-world
        source: pull

    - name: Run hello-world container and display output
      command: docker run --rm hello-world
      register: hello_world_output

    - name: Display hello-world output
      debug:
        var: hello_world_output.stdout